# Generated by Django 2.2.6 on 2020-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='book_handled',
            field=models.ManyToManyField(to='p_library.Book'),
        ),
    ]
