# Generated by Django 2.2.6 on 2020-03-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_reader_book_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(to='p_library.Reader'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='book_handled',
            field=models.ManyToManyField(related_name='handled_books', to='p_library.Book'),
        ),
    ]
