# Generated by Django 2.2.6 on 2020-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200323_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(blank=True, null=True, to='p_library.Reader'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='book_handled',
            field=models.ManyToManyField(blank=True, null=True, related_name='handled_books', to='p_library.Book'),
        ),
    ]
