# Generated by Django 2.2.6 on 2020-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200323_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(blank=True, to='p_library.Reader'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='book_handled',
            field=models.ManyToManyField(blank=True, related_name='handled_books', to='p_library.Book'),
        ),
    ]
